version: "3.9"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python3.9 manage.py runserver 5.188.77.107:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db