# Generated by Django 2.2.5 on 2022-03-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('ymap_id', models.IntegerField()),
                ('address', models.CharField(max_length=1024, verbose_name='Адресс')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('reviews_number', models.IntegerField()),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('subcategory', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('phone_numbers', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('vk', models.CharField(max_length=255, verbose_name='VK')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
            ],
        ),
    ]
